version: 2

models:
  - name: stg_crypto_prices
    description: >
      Staging table for cryptocurrency prices.
      Clean, typed, and validated data from raw source.
    
    columns:
      - name: crypto_id
        description: Unique cryptocurrency identifier
        tests:
          - not_null
          - unique
      
      - name: symbol
        description: Trading symbol (e.g., BTC, ETH)
        tests:
          - not_null
      
      - name: crypto_name
        description: Full cryptocurrency name
        tests:
          - not_null
      
      - name: price_usd
        description: Current price in USD
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
              config:
                severity: error
      
      - name: market_cap_usd
        description: Market capitalization in USD
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0 OR market_cap_usd IS NULL"
      
      - name: volume_24h_usd
        description: 24-hour trading volume
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0 OR volume_24h_usd IS NULL"
      
      - name: price_change_pct_24h
        description: 24-hour price change percentage
        tests:
          - dbt_utils.expression_is_true:
              expression: "BETWEEN -100 AND 10000"
              config:
                severity: warn
      
      - name: price_updated_at
        description: Timestamp when price was last updated
        tests:
          - not_null
      
      - name: dbt_loaded_at
        description: Timestamp when dbt loaded this record
        tests:
          - not_null

    # Model-level tests
    tests:
      - dbt_utils.recency:
          datepart: hour
          field: price_updated_at
          interval: 48
          config:
            severity: warn
